app:
  theme: default
server:
  port: 8080
  
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.ygsm.model.pojo
  configuration:
    map-underscore-to-camel-case: true
  
spring:
    
  freemarker:
    suffix: .html
    content-type: text/html
    charset: UTF-8
    cache: false
    template-loader-path: classpath:/templates
    settings:
      tagSyntax: square_bracket
    
  datasource:
    platform: mysql
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/yg-cms?useUnicode=true&characterEncoding=utf-8
#    platform: h2
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:~/yg-cms/db
    username: root
    password: root
#    initialization-mode: never
#    initialization-mode: always
    
#  h2:
#    console:
#      path: /h2
#      enabled: true

