app:
  user:
    id: 1
    name: aa
    
server:
  tomcat:
    basedir: log
    accesslog:
      enabled: true
      directory: accesslog
      pattern: combined

spring:
  jackson:
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  file:
    path: log/spring
  level:
    web: DEBUG