app:
  user:
    id: 1
    name: aa
    
server:
  tomcat:
    basedir: log
    accesslog:
      enabled: true
      directory: accesslog
      pattern: combined

logging:
  file:
    path: log/spring
  level:
    web: DEBUG